name: Build
on: [push, pull_request]
env:
  buildDir: ${{ github.workspace }}/build/

jobs:
  build:
    runs-on: macos-15 # as of 2025-02-19 latest (aka 14) makes the build fail. yeah, no idea
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'
      - name: Build
        run: |
          gem install --verbose xcpretty
          set -o pipefail && xcodebuild -configuration Release -target "Mumble" CONFIGURATION_BUILD_DIR="${PWD}/__build__" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphoneos | xcpretty
